/**
 * @author Dominic Tardif
 */
package com.example.entrevueSpringBoot.models;

import javax.persistence.*;
import java.util.Objects;

// Defines the 'acteur' table in the database
@Entity
@Table(name = "acteur")
public class Acteur {

    // defines 'id' as the primary key in the database and its value is generated by identity
    // since it is a generated value, no setter are required
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private long id;

    // defines 'nom' as not null in the database
    @Column(name = "nom", nullable = false)
    private String nom;

    // defines 'prenom' as not null in the database
    @Column(name = "prenom", nullable = false)
    private String prenom;

    /**
     * Empty constructor
     */
    public Acteur() {
    }

    /**
     * Parameterized constructor
     * @param nom the last name of the actor
     * @param prenom the first name of the actor
     */
    public Acteur(String nom, String prenom) {
        this.nom = nom;
        this.prenom = prenom;
    }

    public long getId() {
        return id;
    }

    public String getNom() {
        return nom;
    }

    public void setNom(String nom) {
        this.nom = nom;
    }

    public String getPrenom() {
        return prenom;
    }

    public void setPrenom(String prenom) {
        this.prenom = prenom;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        Acteur acteur = (Acteur) o;
        return id == acteur.id && nom.equals(acteur.nom) && prenom.equals(acteur.prenom);
    }

    @Override
    public int hashCode() {
        return Objects.hash(id, nom, prenom);
    }
}
