/**
 * @author Dominic Tardif
 */
package com.example.entrevueSpringBoot.models;

import javax.persistence.*;
import java.util.List;
import java.util.Objects;

// Defines the 'film' table in the database
@Entity
@Table(name = "film")
public class Film {

    // defines 'id' as the primary key in the database and its value is generated by identity
    // since it is a generated value, no setter are required
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private long id;

    // defines 'titre' as not null in the database
    @Column(name = "titre", nullable = false)
    private String titre;

    // defines 'description' as not null in the database
    @Column(name = "description", nullable = false)
    private String description;

    // Relation is one-to-many, i.e. one movie contains multiple actors
    // cascade is used so that actors are saved at the same time as the movie itself
    @OneToMany(targetEntity = Acteur.class, cascade = {CascadeType.ALL})
    private List<Acteur> acteurs;

    /**
     * Empty constructor
     */
    public Film() {
    }

    /**
     * Parameterized constructor
     * @param titre the title of the movie
     * @param description the description of the movie
     * @param acteurs the list of actors in the movie
     */
    public Film(String titre, String description, List<Acteur> acteurs) {
        this.titre = titre;
        this.description = description;
        this.acteurs = acteurs;
    }

    public long getId() {
        return id;
    }

    public String getTitre() {
        return titre;
    }

    public void setTitre(String titre) {
        this.titre = titre;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public List<Acteur> getActeurs() {
        return acteurs;
    }

    public void setActeurs(List<Acteur> acteurs) {
        this.acteurs = acteurs;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        Film film = (Film) o;
        return id == film.id && titre.equals(film.titre) && description.equals(film.description) && acteurs.equals(film.acteurs);
    }

    @Override
    public int hashCode() {
        return Objects.hash(id, titre, description, acteurs);
    }
}
